### ISSUE TITLE
Proximity Sensor in call

### ISSUE THREAD

**Issue by secjournalist** [TomGiordano/android_device_zte_blade#3] opened 2011-02-15 13:55 UTC
Screen does not wake up after phone call.  Have to remove battery.

**Comment by pavilionmedia** [comment] 2011-02-15 14:08
Same here. Seems to happen mainly after incoming calls (and not on very quick ones, either).

**Comment by flibblesan** [comment] 2011-02-15 17:51
Fixed once Tom checks the submission. Issue was caused by incorrect sensor values.

**Comment by TomGiordano** [comment] 2011-02-15 23:17
I doubt the auto-brightness fix that has been submitted for this will actually fix this (but it will fix the auto-brightness which was not configured correctly). I believe screen will wake from this problem if usb is connected, but that is not a very practical fix.
Wait until nightly builds are available and see if the problem still exists.

**Comment by simonckenyon** [comment] 2011-02-16 19:49
built from git about an hour ago and installed on my blade. i suffer from the screen blank after call problem as well. i confirm that connecting to USB restores the screen.

**Comment by TomGiordano** [comment] 2011-02-16 22:50
simonckenyon & pavilionmedia - What version Blade are you using (lcd/tft, 3mp/5mp). This may be related to hardware differences as a few people testing on the Orange San Fran are not experiencing the problem.

Please try using the RC1 build that has just been released. The Blade should be added to the cyanogenmod bug tracker shortly. Once added bug like this should be logged there.

PS. if you are building using this source you should switch to the official source. Fixes will now be submitted through review.cyanogenmod.com and will not be seen in this repository.

**Comment by pavilionmedia** [comment] 2011-02-16 23:21
Using a TFT 3MP. Am downloading RC now and will flash tomorrow and report back if fixed. Thanks.

**Closed as completed** 2011-02-17 06:50 UTC

**Comment by simonckenyon** [comment] 2011-02-17 07:06
I built fron the cyanogenmod repoitory yesterday afternoon.
also tried flibblesan's change. In both cases after making a call the screen remained bkank.
this is with an orange sf (3mp camera and tft display)

In fact using the phone to type this message :-)

**Comment by simonckenyon** [comment] 2011-02-17 08:34
just to be sure. i downloaded rc1 and checked that the proprietary files are the same as in my build. i got them from your vendor_binaries_blade tree.

i notice that Jacob has another set, but having checked they are identical.

so that is not the issue.

another thing. i cleared out all the file systems as stated in some thread. i also made sure to clear the various caches.

will create a log to see what is happening

**Comment by simonckenyon** [comment] 2011-02-17 08:35
i will also try rc1 to see if the problem goes away. maybe i screwed up in the build.

**Comment by simonckenyon** [comment] 2011-02-17 10:27
rc1 made no difference - well it looked prettier than my build - not sure why
but it did not fix the problem

raised it on the cyanogenmod issue tracker (#2851)

**Comment by flibblesan** [comment] 2011-02-17 11:52
the autobrightness changes won't affect the proximity. That is a different issue.

**Comment by simonckenyon** [comment] 2011-02-17 11:58
just posted a log on the issue mentioned above.
i noticed that the log contained the following lines (for a call where the screen "did not come back")

E/Sensors (  167): alsprox sensors_control_activate active=00000022 sensor=00000010 new_sensors=32 changed=10

E/Sensors (  167): alsprox set_prox_threshold_data entered

E/Sensors (  167): alsprox failed to open read prox_threshold_data /data/misc/prox/prox_threshold.txt: No such file or directory (2)

E/Sensors (  167): alsprox set_prox_threshold_data error

not sure if it is relevant

**Comment by simonckenyon** [comment] 2011-02-17 22:07
github says:

 TomGiordano  closed  issue 3 on TomGiordano/android_device_zte_blade  about 23 hours ago

```
Proximity Sensor in call 
```

but i cannot see what changed. am i just being stupid or what?

**Comment by TomGiordano** [comment] 2011-02-17 23:42
I accidentally hit the close button yesterday. The problem is not fixed, but should now be tracked in the cyanogenmod issue tracker.
http://code.google.com/p/cyanogenmod/issues/detail?id=2851

PS. The prox_theshold.txt file appears to not exist in ZTE roms either, so probably wont help. We don't have a template for it so have no idea what should be in it, but I may have a look at the library and see what I can figure out.
